/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LayoutImport } from "./routes/_layout"

// Create Virtual Routes

const LayoutIndexLazyImport = createFileRoute("/_layout/")()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
})

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  path: "/",
  getParentRoute: () => LayoutRoute,
}).lazy(() => import("./routes/_layout/index.lazy").then((d) => d.Route))

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({ LayoutIndexLazyRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.jsx",
      "children": [
        "/_layout/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.lazy.jsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
