"""add new field date_formed to Band

Revision ID: 60eeaf588af2
Revises: 6b139aeae1f5
Create Date: 2024-08-19 12:23:41.798245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60eeaf588af2'
down_revision: Union[str, None] = '6b139aeae1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bands', sa.Column('date_formed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bands', 'date_formed')
    # ### end Alembic commands ###
