"""add new field is_done to Band

Revision ID: 6b139aeae1f5
Revises: 5e3b8b685f83
Create Date: 2024-08-19 12:19:02.946815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6b139aeae1f5"
down_revision: Union[str, None] = "5e3b8b685f83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bands",
        sa.Column(
            "is_done", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bands", "is_done")
    # ### end Alembic commands ###
